import { expect, it } from 'vitest';
import { readFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { collectFixture } from '../src/collectors/fixture.js';
import { calculateKpis } from '../src/analytics/kpis.js';
import { normalizeGithub } from '../src/normalizers/github.js';
import { evaluateDataQuality } from '../src/quality/rules.js';
import { buildSnapshot } from '../src/snapshots/snapshot.js';
import { generateDashboard } from '../src/dashboard/generate.js';
import { loadConfig } from '../src/config.js';

// Vérifie le contrat HTML public du dashboard sans dépendre d'un navigateur.
it('generates static dashboard pages from the snapshot contract', async () => {
  const raw = await collectFixture();
  const featureRequest = raw.repositories[0]!.issues.find((issue) => issue.id === 'issue-101');
  if (!featureRequest) throw new Error('Fixture issue-101 is required for this test.');
  const unconfiguredIssue = structuredClone(featureRequest);
  unconfiguredIssue.id = 'issue-104';
  unconfiguredIssue.number = 104;
  unconfiguredIssue.issueType = 'FEATURE REQUEST';
  unconfiguredIssue.linkedPullRequestIds = [];
  raw.repositories[0]!.issues.push(unconfiguredIssue);
  const config = await loadConfig();
  const normalized = normalizeGithub(raw, config.github, undefined, config.auditVersion);
  const issues = evaluateDataQuality(raw, normalized, config.github);
  const snapshot = buildSnapshot(raw, normalized, issues, calculateKpis(normalized, issues), '2.1', 'dq-test', 'test');
  const output = resolve(process.cwd(), 'data/test-dashboard');
  await generateDashboard(snapshot, output, 'https://github.test');
  const html = await readFile(resolve(output, 'dashboard/index.html'), 'utf8');
  expect(html).toContain('Vue d’ensemble');
  expect(html).toContain('design-system-react');
  expect(html).toContain('design-system-docs');
  expect(html).toContain('Délai moyen');
  expect(html).toContain('Temps de correction par repository');
  expect(html).toContain('Critères d’accessibilité');
  expect(html).toContain('focus');
  expect(html).toContain('Les indicateurs sont calculés dans le pipeline puis expliqués ici avec leur périmètre, leur ratio et leur fiabilité.');
  expect(html).toContain('Couverture des audits');
  expect(html).toContain('Fiabilité par métrique');
  expect(html).toContain('Pourquoi certains chiffres sont partiels');
  expect(html).not.toContain('Count of anomalies retained after DQ exclusions.');
  expect(html).toContain('window.__SNAPSHOT__');
  expect(html).toContain('class="sidebar"');
  expect(html).toContain('ArchInsight');
  expect(html).toContain('Direction / synthèse');
  expect(html).toContain('Audits &amp; versions');
  expect(html).toContain('Patrimoine composants');
  expect(html).toContain('assets/logo.svg');
  const componentsHtml = await readFile(resolve(output, 'dashboard/components.html'), 'utf8');
  expect(componentsHtml).toContain('Référentiel des composants');
  expect(componentsHtml).toContain('data-component-status-filter');
  expect(componentsHtml).toContain('Anomalies ouvertes');
  const squadHtml = await readFile(resolve(output, 'dashboard/squad.html'), 'utf8');
  expect(squadHtml).toContain('Activité Squad');
  expect(squadHtml).toContain('Statuts et planification observés');
  expect(squadHtml).toContain('Velocity source');
  expect(squadHtml).toContain('data-activity-status');
  const auditsHtml = await readFile(resolve(output, 'dashboard/audits.html'), 'utf8');
  expect(auditsHtml).toContain('Périmètre auditable');
  expect(auditsHtml).toContain('Component × Version → Audit → Anomalies');
  expect(auditsHtml).toContain('Composants actifs');
  expect(auditsHtml).toContain('Couverture');
  expect(auditsHtml).toContain('Traçabilité de chaque Audit');
  expect(auditsHtml).toContain('Component / source');
  expect(auditsHtml).toContain('Verdict applicable');
  expect(auditsHtml).toContain('design-system-react');
  const anomaliesHtml = await readFile(resolve(output, 'dashboard/anomalies.html'), 'utf8');
  expect(anomaliesHtml).toContain('Anomalies suivies');
  expect(anomaliesHtml).toContain('href="https://github.test/example/design-system-core/issues/101"');
  expect(anomaliesHtml).toContain('href="https://github.test/example/design-system-core/issues/104"');
  expect(anomaliesHtml).toContain('href="https://github.test/example/design-system-core/pull/201"');
  expect(anomaliesHtml).toContain('<th>PR</th>');
  expect(anomaliesHtml).toContain('<th>Catégorie</th>');
  expect(anomaliesHtml).toContain('<th>Origine</th>');
  expect(anomaliesHtml).toContain('data-criticality="major"');
  expect(anomaliesHtml).toContain('data-categories="focus"');
  expect(html).toContain('href="anomalies.html?criticality=major"');
  expect(html).toContain('href="anomalies.html?category=focus"');
  expect(anomaliesHtml).toContain('Cible : anomalie');
  expect(anomaliesHtml).toContain('Ouvrir la source');
  expect(anomaliesHtml).toContain('Aucune source GitHub disponible (nexus)');
  expect(anomaliesHtml).toContain('DQ-021');
  expect(anomaliesHtml).not.toContain('<p>Anomaly has no criticality.</p>');
  expect(anomaliesHtml).toContain('Issue Type à déclarer : FEATURE REQUEST');
  expect(anomaliesHtml).toContain('Copier le YAML');
  expect(anomaliesHtml).toContain('data-copy-yaml=');
  expect(anomaliesHtml).toContain('data-filter-repository');
  expect(anomaliesHtml).toContain('data-filter-criticality');
  expect(anomaliesHtml).toContain('data-reset-filters');
  const graphHtml = await readFile(resolve(output, 'dashboard/graph.html'), 'utf8');
  expect(graphHtml).toContain('Repository → composant → audit → anomalie → PR');
  expect(graphHtml).toContain('assets/graph.js');
  expect(graphHtml).toContain('Patrimoine et chaîne de preuve');
  expect(graphHtml).toContain('data-map-filter');
  expect(graphHtml).toContain('data-map-kind-filter');
  expect(graphHtml).toContain('map-repository');
  expect(graphHtml).toContain('map-component');
  expect(graphHtml).toContain('map-node');
  expect(graphHtml).toContain('PR liée');
  const historyHtml = await readFile(resolve(output, 'dashboard/history.html'), 'utf8');
  expect(historyHtml).toContain('À la Release vs connaissance actuelle');
  expect(historyHtml).toContain('État à la Release');
  const graphScript = await readFile(resolve(output, 'dashboard/assets/graph.js'), 'utf8');
  expect(graphScript).toContain('data-map-node');
  expect(graphScript).toContain('data-map-kind-filter');
  const logo = await readFile(resolve(output, 'dashboard/assets/logo.svg'), 'utf8');
  expect(logo).toContain('<svg');
  const appScript = await readFile(resolve(output, 'dashboard/assets/app.js'), 'utf8');
  expect(appScript).toContain('sortableTables');
  expect(appScript).toContain('aria-sort');
  expect(appScript).toContain('data-reset-activity-filters');
  await rm(output, { recursive: true, force: true });
});
