import { expect, it } from 'vitest';
import { readFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { collectFixture } from '../src/collectors/fixture.js';
import { calculateKpis } from '../src/analytics/kpis.js';
import { normalizeGithub } from '../src/normalizers/github.js';
import { evaluateDataQuality } from '../src/quality/rules.js';
import { buildSnapshot } from '../src/snapshots/snapshot.js';
import { generateDashboard } from '../src/dashboard/generate.js';
import { loadConfig } from '../src/config.js';

// Vérifie le contrat HTML public du dashboard sans dépendre d'un navigateur.
it('generates static dashboard pages from the snapshot contract', async () => {
  const raw = await collectFixture();
  const config = await loadConfig();
  const normalized = normalizeGithub(raw, config.github);
  const issues = evaluateDataQuality(raw, normalized, config.github);
  const snapshot = buildSnapshot(raw, normalized, issues, calculateKpis(normalized, issues), '2.1', 'dq-test', 'test');
  const output = resolve(process.cwd(), 'data/test-dashboard');
  await generateDashboard(snapshot, output, 'https://github.test');
  const html = await readFile(resolve(output, 'dashboard/index.html'), 'utf8');
  expect(html).toContain('Vue d’ensemble');
  expect(html).toContain('design-system-react');
  expect(html).toContain('design-system-docs');
  expect(html).toContain('Délai moyen de correction');
  expect(html).toContain('Temps de correction par repository');
  expect(html).toContain('Critères d’accessibilité');
  expect(html).toContain('focus');
  expect(html).toContain('Nombre d’anomalies conservées après les exclusions de qualité des données.');
  expect(html).not.toContain('Count of anomalies retained after DQ exclusions.');
  expect(html).toContain('window.__SNAPSHOT__');
  const anomaliesHtml = await readFile(resolve(output, 'dashboard/anomalies.html'), 'utf8');
  expect(anomaliesHtml).toContain('Anomalies suivies');
  expect(anomaliesHtml).toContain('href="https://github.test/example/design-system-core/issues/101"');
  expect(anomaliesHtml).toContain('href="https://github.test/example/design-system-core/pull/201"');
  expect(anomaliesHtml).toContain('PR liées');
  expect(anomaliesHtml).toContain('<th>Catégorie</th>');
  expect(anomaliesHtml).toContain('data-criticality="major"');
  expect(anomaliesHtml).toContain('data-categories="focus"');
  expect(html).toContain('href="anomalies.html?criticality=major"');
  expect(html).toContain('href="anomalies.html?category=focus"');
  expect(anomaliesHtml).toContain('Cible : anomalie');
  expect(anomaliesHtml).toContain('Ouvrir la source');
  expect(anomaliesHtml).toContain('Aucune source GitHub disponible (nexus)');
  expect(anomaliesHtml).toContain('L’anomalie n’a pas de criticité.');
  expect(anomaliesHtml).not.toContain('<p>Anomaly has no criticality.</p>');
  expect(anomaliesHtml).toContain('Copier le YAML');
  expect(anomaliesHtml).toContain('data-copy-yaml=');
  await rm(output, { recursive: true, force: true });
});
