import type { RawDataset, RawIssue, RawPullRequest, RawRepository } from '../domain/types.js';
import { createStableMapper } from './mapping.js';
import type { AnonymizationOptions, AnonymizationReport, AnonymizationResult } from './types.js';
import { sanitizeText } from './sanitize.js';
const MS_PER_DAY=86_400_000;
function shiftDate(value:string|undefined,offsetDays:number,report:AnonymizationReport):string|undefined { if(!value)return undefined; const d=new Date(value); if(Number.isNaN(d.getTime()))return value; report.datesShifted++; return new Date(d.getTime()+offsetDays*MS_PER_DAY).toISOString(); }
function mappedNumber(seedMapper:ReturnType<typeof createStableMapper>,namespace:string,repository:string,n:number,prefix:string):number { return Number.parseInt(seedMapper(namespace,`${repository}:${n}`,prefix).slice(2),16)%900000+100000; }
function mapComponent(name:string,options:AnonymizationOptions,map:ReturnType<typeof createStableMapper>):string { return options.preserveComponentNames?name:map('component',name,'component'); }
function mapLabels(labels:string[],options:AnonymizationOptions,map:ReturnType<typeof createStableMapper>):string[] { return labels.map(label=>{ const m=/^Component:(.+)$/i.exec(label); if(m)return `Component:${mapComponent(m[1],options,map)}`; if(/^(a11y|rgaa|severity|category):/i.test(label))return label; return `label:${map('label',label,'anon')}`; }); }
function anonymizeIssue(issue:RawIssue,repo:string,options:AnonymizationOptions,map:ReturnType<typeof createStableMapper>,report:AnonymizationReport):RawIssue { const title=options.strictText?'[anonymized issue]':sanitizeText(issue.title,options).value; if(title!==issue.title)report.textsSanitized++; return {...issue,id:map('issue',`${repo}:${issue.id}`,'issue'),number:mappedNumber(map,'issue-number',repo,issue.number,'n'),title,labels:mapLabels(issue.labels,options,map),component:issue.component?mapComponent(issue.component,options,map):undefined,parents:issue.parents.map(x=>map('issue',`${repo}:${x}`,'issue')),createdAt:shiftDate(issue.createdAt,options.dateOffsetDays,report)!,closedAt:shiftDate(issue.closedAt,options.dateOffsetDays,report),firstDoneAt:shiftDate(issue.firstDoneAt,options.dateOffsetDays,report),linkedPullRequestIds:issue.linkedPullRequestIds.map(x=>map('pr',`${repo}:${x}`,'pr')),projectStatuses:issue.projectStatuses.map(x=>({...x,projectId:map('project',x.projectId,'project'),projectName:options.strictText?`project-${map('project-name',x.projectName,'anon')}`:sanitizeText(x.projectName,options).value})),milestone:issue.milestone?{...issue.milestone,id:mappedNumber(map,'milestone',repo,issue.milestone.id,'m'),title:options.strictText?`milestone-${map('milestone-title',issue.milestone.title,'anon')}`:sanitizeText(issue.milestone.title,options).value}:undefined}; }
function anonymizePullRequest(pr:RawPullRequest,repo:string,options:AnonymizationOptions,map:ReturnType<typeof createStableMapper>,report:AnonymizationReport):RawPullRequest { return {...pr,id:map('pr',`${repo}:${pr.id}`,'pr'),number:mappedNumber(map,'pr-number',repo,pr.number,'n'),mergedAt:shiftDate(pr.mergedAt,options.dateOffsetDays,report),relatedIssueIds:pr.relatedIssueIds.map(x=>map('issue',`${repo}:${x}`,'issue'))}; }
export function anonymizeDataset(input:RawDataset,options:AnonymizationOptions):AnonymizationResult { const map=createStableMapper(options.seed); const report:AnonymizationReport={repositories:input.repositories.length,issues:input.repositories.reduce((n,r)=>n+r.issues.length,0),pullRequests:input.repositories.reduce((n,r)=>n+r.pullRequests.length,0),components:input.catalogueComponents.length,ownersAnonymized:input.repositories.length,repositoryNamesAnonymized:input.repositories.length,idsAnonymized:0,datesShifted:0,textsSanitized:0,suspiciousStrings:0,warnings:[]}; const repositories:RawRepository[]=input.repositories.map(r=>({...r,id:map('repository-id',r.id,'repo'),name:map('repository',r.name,'repo'),owner:map('owner',r.owner,'owner'),issues:r.issues.map(i=>anonymizeIssue(i,r.name,options,map,report)),pullRequests:r.pullRequests.map(pr=>anonymizePullRequest(pr,r.name,options,map,report))})); const dataset:RawDataset={...input,collectedAt:shiftDate(input.collectedAt,options.dateOffsetDays,report)!,repositories,catalogueComponents:input.catalogueComponents.map(x=>mapComponent(x,options,map))}; report.idsAnonymized=report.issues+report.pullRequests+report.repositories; return {dataset,report}; }
